package com.cars_showroom.db.cars_showroom_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE Showroom_listBase PLEASE EDIT ../Showroom_list.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Showroom_list object
 * 
 */
 
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import java.util.Date;
import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

import org.mongodb.morphia.annotations.Id;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.cars_showroom.utils.ObjectIdListSerializer;


//IMPORT RELATIONS
import com.cars_showroom.db.cars_showroom_db.entity.Cars_list;
import com.cars_showroom.db.cars_showroom_db.entity.Showroom_list;

@Entity("Showroom_list")
public class Showroom_listBase {
	
	@Id
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId _id;
	
	// Attributes
    private String showroom_name;
	
	
	// Relations cars_list
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId cars_list;
	
	
	
	

    // GETTER AND SETTER
    
	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId id) {
		this._id = id;
	}


	
	public String getShowroom_name() {
		return showroom_name;
	}


	public void setShowroom_name(String showroom_name) {
		this.showroom_name = showroom_name;
	}
    

	
    
    // Relations 1:m cars_list
	public ObjectId getCars_list() {
		return cars_list;
	}

	public void setCars_list(ObjectId cars_list) {
		this.cars_list = cars_list;
	}
    
    
    
    
}